export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SIGNUP = "SIGNUP";
export const GET_USER = "GET_USER";
export const GET_USERS = "GET_USERS";
export const EDIT_USER = "EDIT_USER";

//graph/survey interaction
export const COMPLETE_SURVEY = "COMPLETE_SURVEY";
export const GET_USER_GRAPH = "GET_USER_GRAPH";

//journal
export const ADD_TO_JOURNAL = "ADD_TO_JOURNAL";
export const GET_USER_JOURNAL = "GET_USER_JOURNAL";
export const LOGOUT_JOURNAL = "LOGOUT_JOURNAL";
export const EDIT_USER_JOURNAL = "EDIT_USER_JOURNAL";

//Request Counselor
export const REQUEST_COUNSELOR = "REQUEST_COUNSELOR";
export const GET_REQUESTED_USERS = "GET_REQUESTED_USERS,";
export const CHECK_IF_REQUESTED = "CHECK_IF_REQUESTED";
export const REJECT_REQUEST = "REJECT_REQUEST";
export const ACCEPT_REQUEST = "ACCEPT_REQUEST";
export const GET_ACCEPTED_USERS = "GET_ACCEPTED_USERS";
export const GET_ACCEPTED_COUNSELORS = "GET_ACCEPTED_USERS";
export const LOGOUT_REQUEST_COUNSELOR = "LOGOUT_REQUEST_COUNSELOR";
export const GET_MATCHING_USER_COUNSELOR = "GET_MATCHING_USER_COUNSELOR"

//twilio
export const SEND_TEXT = 'SEND_TEXT'

//????
export const GET_QUOTES = "GET_QUOTES";

export const LOGIN_COUNSELOR = "LOGIN_COUNSELOR";
export const LOGOUT_COUNSELOR = "LOGOUT_COUNSELOR";
export const SIGNUP_COUNSELOR = "SIGNUP_COUNSELOR";
export const GET_COUNSELORS = "GET_COUNSELORS";
export const EDIT_COUNSELOR = "EDIT_COUNSELOR";
